# Generated by Django 4.2 on 2023-08-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_tolov_qaysi_oy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('merchant', models.CharField(max_length=100)),
                ('attributes', models.ManyToManyField(to='dashboard.attribute')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.image')),
            ],
        ),
        migrations.RemoveField(
            model_name='oylik',
            name='ustoz',
        ),
        migrations.RemoveField(
            model_name='shogirt',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='shogirt',
            name='ustoz',
        ),
        migrations.RemoveField(
            model_name='tolov',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='tolov',
            name='shogirt',
        ),
        migrations.RemoveField(
            model_name='tolov',
            name='ustoz',
        ),
        migrations.RemoveField(
            model_name='ustoz',
            name='fan',
        ),
        migrations.DeleteModel(
            name='Avans',
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.DeleteModel(
            name='Oylik',
        ),
        migrations.DeleteModel(
            name='Shogirt',
        ),
        migrations.DeleteModel(
            name='Tolov',
        ),
        migrations.DeleteModel(
            name='Ustoz',
        ),
    ]
